### ISSUE TITLE
Discord player type error

### ISSUE THREAD

**Issue by ZpeedTube** [TannerGabriel/discord-bot#215] opened 2023-03-14 20:24 UTC
Not sure if this is a bug in the bot or in the discord player but I thought I should mention/ask here.

**Describe the bug**
I tried installing the bot with the current master branch. Only updated 2 packages:
```json
    "discord-player": "^6.1.0",
    "discord.js": "^14.8.0",
```
but I get this error:
```
***\discord-bot\node_modules\discord-player\dist\index.js:2095
  if (import_voice4.version.includes("-dev") || import_voice4.version.startsWith("1"))
                            ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at C:\nodejs\bots\discord-bot\node_modules\discord-player\dist\index.js:2095:29
    at Object.<anonymous> (C:\nodejs\bots\discord-bot\node_modules\discord-player\dist\index.js:2099:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\nodejs\bots\discord-bot\index.js:7:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

**To Reproduce**
1. install bot from master (followed steps in tutorial)
2. install node packages and update discord-player & discord.js
3. configure the config.json file
4. try running `node index.js`

**Expected behavior**
Be able to run the bot without errors.

**What actually happens**
I get the error I mentioned in the code block above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CPU architecture: x86

**Dependency versions:**
 - Nodejs version: 16.13.2
 - YTDL-core version: ^4.11.2

Aditonall info:
Also tested Node 18.15.0 but I get the exact same problem.
And seems like I'm not the only one with this problem, check this StackOverflow question: https://stackoverflow.com/questions/75716977/discord-player-typeerror-cannot-read-properties-of-undefined-reading-include

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by bestpie1** [comment] 2023-03-15 05:38
I also have this problem and want to know if there is a fix for this.

**Comment by ZpeedTube** [comment] 2023-03-17 22:27
Ah okay

**Comment by skdhg** [comment] 2023-04-06 14:59
This is due to malformed installation caused by npm. The solution is to clean install all packages or use another package manager like yarn.

**Closed** 2023-05-13 00:14 UTC
Labels: no-issue-activity
