### ISSUE TITLE
discord.js Opus

### ISSUE THREAD

**Issue by Radjejszyn** [TannerGabriel/discord-bot#89] opened 2021-09-14 20:20 UTC
**Describe the bug**
cant play song

**To Reproduce**
1. install the bot
2. launch the bot
3. 

**Expected behavior**
to play song 

**Desktop (please complete the following information):**
 - OS: [debian-10-buster-v20210817]
 - CPU architecture: [e.g. x64]

**Dependency versions:**
 - Nodejs version: [e.g. 10]
 - YTDL-core version: [e.g. 4.4.5]

**Additional context (optional)**
- /home/g1kacper_wysocki/discord-bot/node_modules/discord-player/dist/Player.js
- /home/g1kacper_wysocki/discord-bot/node_modules/discord-player/dist/index.js
- /home/g1kacper_wysocki/discord-bot/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/node_modules/prism-media/src/util/loader.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/node_modules/prism-media/src/opus/Opus.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/node_modules/prism-media/src/opus/index.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/node_modules/prism-media/src/index.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/dist/audio/TransformerGraph.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/dist/audio/AudioResource.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/dist/audio/index.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/dist/index.js
- /home/g1kacper_wysocki/discord-bot/node_modules/discord-player/dist/Structures/Queue.js
- /home/g1kacper_wysocki/discord-bot/node_modules/discord-player/dist/Player.js
- /home/g1kacper_wysocki/discord-bot/node_modules/discord-player/dist/index.js
- /home/g1kacper_wysocki/discord-bot/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/node_modules/prism-media/src/util/loader.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/node_modules/prism-media/src/opus/Opus.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/node_modules/prism-media/src/opus/index.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/node_modules/prism-media/src/index.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/dist/audio/TransformerGraph.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/dist/audio/AudioResource.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/dist/audio/index.js
- /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/dist/index.js
- /home/g1kacper_wysocki/discord-bot/node_modules/discord-player/dist/Structures/Queue.js
- /home/g1kacper_wysocki/discord-bot/node_modules/discord-player/dist/Player.js
- /home/g1kacper_wysocki/discord-bot/node_modules/discord-player/dist/index.js
- /home/g1kacper_wysocki/discord-bot/index.js
    at Object.loader [as require] (/home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Encoder (/home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/node_modules/prism-media/src/opus/Opus.js:149:5)
    at Object.transformer (/home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/dist/audio/TransformerGraph.js:120:24)
    at /home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/dist/audio/AudioResource.js:158:60
    at Array.map (<anonymous>)
    at Object.createAudioResource (/home/g1kacper_wysocki/discord-bot/node_modules/@discordjs/voice/dist/audio/AudioResource.js:158:41)
    at StreamDispatcher.createStream (/home/g1kacper_wysocki/discord-bot/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:108:38)
    at Queue.<anonymous> (/home/g1kacper_wysocki/discord-bot/node_modules/discord-player/dist/Structures/Queue.js:663:46)
/home/g1kacper_wysocki/discord-bot/node_modules/discord.js/src/rest/RequestHandler.js:298
      throw new DiscordAPIError(data, res.status, request);

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by TannerGabriel** [comment] 2021-09-15 06:20
Are you running the application without Docker? If so, could you make sure that you have Opus and FFMPEG installed on your machine?

**Comment by Radjejszyn** [comment] 2021-09-15 06:44
> Are you running the application without Docker? If so, could you make sure that you have Opus and FFMPEG installed on your machine?

I'm running it on Google cloud machine on Debian. I have ffmpeg installed and opus.
I would like to use docker but I don't have any clue how it works and I can't find any good online tutorial how to install it on docker

**Comment by TannerGabriel** [comment] 2021-09-15 06:46
@Radjejszyn I can recommend this [DigitalOcean tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04) for installing Docker on Ubuntu (Debian).

**Comment by Radjejszyn** [comment] 2021-09-15 06:48
> @Radjejszyn I can recommend this [DigitalOcean tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04) for installing Docker on Ubuntu (Debian).

Oh okay, thanks I will look into in when I come home, should I close the issue?

**Comment by TannerGabriel** [comment] 2021-09-15 06:50
You can close it if you like, but you could also leave it open until we find the cause of the problem.

**Comment by Radjejszyn** [comment] 2021-09-15 06:51
Okay sure

**Comment by Radjejszyn** [comment] 2021-09-15 20:54
> You can close it if you like, but you could also leave it open until we find the cause of the problem.

Error: Cannot find module 'discord.js'
Require stack:
- /home/g1kacper_wysocki/discord-bot/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/g1kacper_wysocki/discord-bot/index.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/g1kacper_wysocki/discord-bot/index.js' ]
}
root@dcbot:/home/g1kacper_wysocki/discord-bot# node index.js

this is error which i got now

**Comment by Radjejszyn** [comment] 2021-09-15 21:45
okay i got it working, but i have a question. why do i cant use my commands with prefix for example ?skip (i have changed it to ?)

**Comment by Asemco** [comment] 2021-09-16 07:05
Hey @Radjejszyn, check out Issue #88 for the answer.

Long story short: It's coming (back) soon™ :)

**Comment by Ao1Pointblank** [comment] 2021-09-16 13:18
I think you need to install node-opus and opusscript manually (i had to, to get mine working)

try:
npm install node-opus opusscript

otherwise the bot can't play audio.

**Closed** 2021-09-16 14:39 UTC
