### ISSUE TITLE
Bot skips to next song after 7 minutes

### ISSUE THREAD

**Issue by Sami236** [TannerGabriel/discord-bot#290] opened 2024-09-17 09:01 UTC
**Describe the bug**
When I play a song with more than 7 minutes of playtime, and I add a song in the queue after that, the first song im playing only plays for 7 minutes and then skips to the next song in the queue without warning.

**To Reproduce**
1. Play a song that lasts longer than 7 minutes. I played one that took 9 minutes
2. Add another song to the queue with the play command (I added another song that took 9 minutes)
3. After 7 minutes, the first song should automatically skip to the next one even when it was not finished

**Expected behavior**
I expect the first song to finish playing fully before going to the next song.

**Screenshots (optional)**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CPU architecture: x64

**Dependency versions:**
 - Nodejs version: 20.17.0
 - YTDL-core version: 4.14.4

**Additional context (optional)**
N/A

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by Sami236** [comment] 2024-09-19 07:55
After further testing, when it just skips is completely random, sometimes it can even skip after 3 minutes

**Comment by H-Fizzle** [comment] 2024-10-11 11:09
Ive got a similar issue, plays 2/3 of a song then stops, no apparent errors.
Running the latest version of the bot on docker, such a shame as this semes to be the best music bot ive found.

**Comment by TannerGabriel** [comment] 2024-11-12 08:46
I couldn’t reproduce the issue myself, but I suspect it may be related to ytdl-core or the YouTube extractor being outdated. I've created two branches that might resolve the problem. If you have time, please try them out and let me know how it goes:

- `fix/song-skip` - Update the dependencies and remove unneeded `opusscript`
- `fix/skip-song-extractor`   - Also switch to another extractor since the discord-player one is marked as unstable

**Comment by H-Fizzle** [comment] 2024-11-12 11:56
Downloaded and built the docker image, so far the issue persists. i'm able to get 60% of the way through a song but then the bot just dissconects. 

No errors seem to pop up when running the docker container in a shell. All i get is 

WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".

any ideas?

**Closed as not planned** 2024-12-19 00:22 UTC
Labels: no-issue-activity
