### ISSUE TITLE
Bot skipping tracks on occasion

### ISSUE THREAD

**Issue by TurtleY0da** [TannerGabriel/discord-bot#122] opened 2021-09-22 05:21 UTC
The bot works great, when it works. All I know is that on occasion, it will say that it started playing the video, and then immediately go to the next song (or if only 1 video was queued, it will immediately say that the queue is finished, and will disconnect). It does not, however, seem random, as it seems like the same videos are being skipped every time. Additionally, I don't receive any errors on the console, other than "[Test Server] Error emitted from the queue: write EPIPE"

If it's a fault on my end, please let me know, otherwise, please look into this issue.

**Comment by QWERTY-exe** [comment] 2021-09-24 09:04
I also have a similar issue. In the terminal log, the following lines would appear after about 15 minutes of playing:
Error emitted from the queue: aborted
Error emitted from the connection: aborted

**Comment by corporatony** [comment] 2021-10-15 15:56
I've had this same issue. I'm not able to determine what is causing it

**Comment by willm132** [comment] 2021-10-16 02:26
Anyone have a fix for this?

**Comment by TannerGabriel** [comment] 2021-10-16 11:04
Thank you for continuing this thread. I believe that this might be an issue with the `discord-player` library used in this repository. I will take a closer look and might create an issue on that repository if I can confirm my suspicion.

**Comment by TannerGabriel** [comment] 2021-10-19 19:05
This seems to be a [known issue](https://github.com/Androz2091/discord-player/issues/818) with the current `discord-player` version and is under investigation.

**Comment by rorobig** [comment] 2021-10-31 15:39
try this
https://github.com/TannerGabriel/discord-bot/pull/138/commits/cc0a88bc999ba33820f352e9930771cce6cfbaaf

**Comment by QWERTY-exe** [comment] 2021-11-02 09:32
It appears to be working as of now, as I am yet to encounter a problem with it. Unless there are cases otherwise, I think this should suffice.

**Comment by TannerGabriel** [comment] 2021-11-02 16:12
@QWERTY-exe Thank you for the feedback. I will close the issue for now since it seems to be working. If anyone encounters another instance of the problem feel free to write a comment and I will reopen it.

**Closed by TannerGabriel** 2021-11-02 16:12 UTC
Labels: bug, help wanted

**Comment by QWERTY-exe** [comment] 2022-06-18 12:25
After a bit of testing, this issue has seemed to resurface. It requires the bot to play about half an hour, but once it does, the terminal shows...

Error emitted from the queue: aborted
Error emitted from the connection: aborted

the exact same message that happened previously. Perhaps this has to do with a ytdl-core update.
